### ISSUE TITLE
Disable Reactions globally and only allow in some channels

### ISSUE THREAD

**Issue by db2k** [Devcord/community#3]
I guess emoji reaction spamming can be annoying in some channels/topics.
What do you think?

**Comment by thorerik** [comment]
Is it such a big issue though? IMO it's better than just plain emoji replies than a bunch of reactions, also gives a relation what it was to.

**Comment by db2k** [comment]
I would at least disable emoji reactions in channels which are only for bot-commands, the feedback channel, support and welcome since they are only information channels and not really about discussion. What do you think?

**Comment by db2k** [comment]
Done!
